// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wzuglyydxdunvzdgxbzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dWdseXlkeGR1bnZ6ZGd4Ynp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTUzMDEsImV4cCI6MjA3MDgzMTMwMX0.BhbXp-tY7qjSQ05M48ajhHAjAR3hIg9T6vMzx15z0jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);